export const universidades: Object = {
    administracion: 'Administración de Empresas',
    antropologia: 'Antropología',
    biologia: 'Biología',
    cienciapolitica: 'Ciencia Política',
    derecho: 'Derecho',
    dmi: 'Diseño de Medios Interactivos',
    di: 'Diseño Industrial',
    licenciatura: 'Licenciatura',
    economia: 'Economía',
    Bioquímica: 'Bioquímica',
    Sistemas: 'Sistemas',
    IIndustrial: 'Ingeniería Industrial',
    Telemática: 'Telemática',
    Medicina: 'Medicina',
    Psicología: 'Psicología',
    mercadeo: 'Mercadeo Internacional y Publicidad',
    Química: 'Química',
    Música: 'Música',
    Sociología: 'Sociología',
    
};